development:
  adapter: postgresql
  encoding: utf8
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  pool: 5

cucumber:
  <<: *TEST